import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { renderAgentAdapter, AGENTS_MD_RELATIVE_PATH } from "../src/adapters/agent/render.js";
import type { ResolvedPackEntry } from "../src/packs/resolve-packs.js";

function writeFile(path: string, content: string): void {
  mkdirSync(join(path, ".."), { recursive: true });
  writeFileSync(path, content, "utf8");
}

function makePackEntry(packsRoot: string, name: string, skills: string[]): ResolvedPackEntry {
  const path = join(packsRoot, name);
  return {
    name,
    path,
    manifest: { name, displayName: `${name} display`, description: `${name} description`, requires: [], skills, adapters: ["claude", "cursor", "copilot", "agent"] },
    installable: true,
    skills: skills.map((s) => ({ name: s, hasContent: true })),
  };
}

describe("renderAgentAdapter (spec §8.5, decisions.md D1/D19/D24)", () => {
  let packsRoot: string;
  let targetDir: string;

  beforeEach(() => {
    packsRoot = mkdtempSync(join(tmpdir(), "inject-nockta-skills-agent-packs-"));
    targetDir = mkdtempSync(join(tmpdir(), "inject-nockta-skills-agent-target-"));
  });

  afterEach(() => {
    rmSync(packsRoot, { recursive: true, force: true });
    rmSync(targetDir, { recursive: true, force: true });
  });

  function writeSkill(pack: string, skill: string, content: string, supportedAdapters = ["claude", "cursor", "copilot", "agent"], agentOutputs = true): void {
    const skillDir = join(packsRoot, pack, "skills", skill);
    writeFile(join(skillDir, "SKILL.md"), content);
    writeFile(
      join(skillDir, "skill.json"),
      JSON.stringify({
        name: skill,
        supportedAdapters,
        outputs: {
          claude: { skills: true },
          cursor: supportedAdapters.includes("cursor") ? { skills: true } : false,
          copilot: supportedAdapters.includes("copilot") ? { skills: true } : false,
          agent: supportedAdapters.includes("agent") ? { skills: agentOutputs, agents: true } : false,
        },
      }),
    );
  }

  it("renders exactly ONE root AGENTS.md with a Nockta-generated intro, sections per pack", () => {
    writeSkill("pack-a", "skill-a", "# Skill A body");
    writeSkill("pack-b", "skill-b", "# Skill B body");
    const packs = [makePackEntry(packsRoot, "pack-a", ["skill-a"]), makePackEntry(packsRoot, "pack-b", ["skill-b"])];

    const result = renderAgentAdapter({ targetDir, packs, packsRoot, effectiveSkills: new Set(["skill-a", "skill-b"]) });

    expect(result.written.length).toBe(1);
    const outputPath = join(targetDir, "AGENTS.md");
    expect(existsSync(outputPath)).toBe(true);
    const content = readFileSync(outputPath, "utf8");
    // D34 addendum: the whole Nockta payload is wrapped in a guard region (the merge seam) — the
    // file now OPENS with the region marker, and the intro header follows immediately inside it.
    expect(content.startsWith("<!-- nockta:agents:start -->\n# AGENTS.md")).toBe(true);
    expect(content).toMatch(/Generated by \[inject-nockta-skills\]/);
    // D34: standing-mode contract is the preamble (single source of truth for the block).
    expect(content).toMatch(/<!-- nockta:standing-mode:start -->/);
    expect(content).toMatch(/Working mode — Nockta standing contract/);
    expect(content).toMatch(/# Skill A body/);
    expect(content).toMatch(/# Skill B body/);
    expect(content).toMatch(/pack-a display/);
    expect(content).toMatch(/pack-b display/);
    // No tool-specific frontmatter block (unlike cursor's YAML frontmatter / copilot's applyTo).
    expect(content.startsWith("---")).toBe(false);

    const record = result.written[0];
    expect(record?.relativePath).toBe(AGENTS_MD_RELATIVE_PATH);
    expect(record?.relativePath).toBe("AGENTS.md");
    expect(record?.adapter).toBe("agent");
    expect(record?.pack).toBe("pack-a,pack-b");
    expect(record?.skill).toBeUndefined();
    expect(record?.kind).toBe("instructions");
  });

  it("D34 addendum: merges into a pre-existing consumer AGENTS.md — never clobbers, flags mergedIntoConsumerContent", () => {
    writeSkill("pack-a", "skill-a", "# Skill A body");
    const packs = [makePackEntry(packsRoot, "pack-a", ["skill-a"])];
    const outputPath = join(targetDir, "AGENTS.md");
    writeFileSync(outputPath, "# Consumer AGENTS\n\nKEEP-THIS-CONSUMER-LINE\n", "utf8");

    const result = renderAgentAdapter({ targetDir, packs, packsRoot, effectiveSkills: new Set(["skill-a"]) });

    const content = readFileSync(outputPath, "utf8");
    expect(content).toContain("KEEP-THIS-CONSUMER-LINE");
    expect(content).toContain("<!-- nockta:agents:start -->");
    expect(content).toMatch(/# Skill A body/);
    expect(result.written[0]?.mergedIntoConsumerContent).toBe(true);
    // `content` field stays target-independent (canonical fresh region), not the merged bytes.
    expect(result.written[0]?.content?.toString("utf8")).not.toContain("KEEP-THIS-CONSUMER-LINE");
  });

  it("D34 addendum: fresh target sets mergedIntoConsumerContent false and wraps the whole payload in the guard region", () => {
    writeSkill("pack-a", "skill-a", "# Skill A body");
    const packs = [makePackEntry(packsRoot, "pack-a", ["skill-a"])];

    const result = renderAgentAdapter({ targetDir, packs, packsRoot, effectiveSkills: new Set(["skill-a"]) });

    const content = readFileSync(join(targetDir, "AGENTS.md"), "utf8");
    expect(content.startsWith("<!-- nockta:agents:start -->")).toBe(true);
    expect(content.trimEnd().endsWith("<!-- nockta:agents:end -->")).toBe(true);
    expect(result.written[0]?.mergedIntoConsumerContent).toBe(false);
  });

  it("adapter-restriction: a claude-only skill is excluded from AGENTS.md, reported skipped", () => {
    writeSkill("pack-a", "claude-only-skill", "# Claude Only", ["claude"]);
    const packs = [makePackEntry(packsRoot, "pack-a", ["claude-only-skill"])];

    const result = renderAgentAdapter({ targetDir, packs, packsRoot, effectiveSkills: new Set(["claude-only-skill"]) });

    expect(result.written).toEqual([]);
    expect(existsSync(join(targetDir, "AGENTS.md"))).toBe(false);
    expect(result.skipped).toEqual([
      { pack: "pack-a", skill: "claude-only-skill", reason: 'adapter-restricted: supportedAdapters=[claude] (no "agent")' },
    ]);
  });

  it("outputs.agent respected: outputs.agent.skills !== true excludes the skill even when supportedAdapters lists agent", () => {
    writeSkill("pack-a", "no-agent-output", "# No agent output", ["claude", "agent"], false);
    const packs = [makePackEntry(packsRoot, "pack-a", ["no-agent-output"])];

    const result = renderAgentAdapter({ targetDir, packs, packsRoot, effectiveSkills: new Set(["no-agent-output"]) });

    expect(result.written).toEqual([]);
    expect(result.skipped).toContainEqual({
      pack: "pack-a",
      skill: "no-agent-output",
      reason: "outputs.agent is false (or undeclared, or outputs.agent.skills is not true)",
    });
  });

  it("D19 selection: a deselected skill is excluded from AGENTS.md, reported skipped", () => {
    writeSkill("pack-a", "excluded-skill", "# Excluded");
    writeSkill("pack-a", "included-skill", "# Included");
    const packs = [makePackEntry(packsRoot, "pack-a", ["excluded-skill", "included-skill"])];

    const result = renderAgentAdapter({ targetDir, packs, packsRoot, effectiveSkills: new Set(["included-skill"]) });

    expect(result.skipped).toContainEqual({
      pack: "pack-a",
      skill: "excluded-skill",
      reason: "excluded by skill selection (not in the effective set, decisions.md D19)",
    });
    const content = readFileSync(join(targetDir, "AGENTS.md"), "utf8");
    expect(content).toMatch(/# Included/);
    expect(content).not.toMatch(/# Excluded/);
  });

  it("D1 override rule: packs/<pack>/adapters/agent/<pack>.md wins wholesale for that pack's section", () => {
    writeSkill("pack-a", "skill-a", "# Base content (should NOT appear)");
    const packs = [makePackEntry(packsRoot, "pack-a", ["skill-a"])];
    const overridePath = join(packsRoot, "pack-a", "adapters", "agent", "pack-a.md");
    writeFile(overridePath, "Hand-authored AGENTS.md section.");

    const result = renderAgentAdapter({ targetDir, packs, packsRoot, effectiveSkills: new Set(["skill-a"]) });

    const content = readFileSync(join(targetDir, "AGENTS.md"), "utf8");
    expect(content).toMatch(/Hand-authored AGENTS\.md section\./);
    expect(content).not.toMatch(/Base content/);
    expect(result.written[0]?.overridden).toBe(true);
  });

  it("zero rendering skills across every pack produces no file at all", () => {
    writeSkill("pack-a", "claude-only-skill", "# Claude Only", ["claude"]);
    const packs = [makePackEntry(packsRoot, "pack-a", ["claude-only-skill"])];

    const result = renderAgentAdapter({ targetDir, packs, packsRoot, effectiveSkills: new Set(["claude-only-skill"]) });

    expect(result.written).toEqual([]);
    expect(existsSync(join(targetDir, "AGENTS.md"))).toBe(false);
  });

  it("D24: agent artifacts (outputs.agent.agents) are NEVER honored — worker.md-type skills only ever contribute skill prose", () => {
    // outputs.agent.agents: true is set but must be ignored; only SKILL.md prose renders, no
    // agent-registration mechanism exists for AGENTS.md.
    writeSkill("pack-a", "artifact-skill", "# Artifact skill prose", ["claude", "agent"], true);
    const packs = [makePackEntry(packsRoot, "pack-a", ["artifact-skill"])];

    const result = renderAgentAdapter({ targetDir, packs, packsRoot, effectiveSkills: new Set(["artifact-skill"]) });

    const content = readFileSync(join(targetDir, "AGENTS.md"), "utf8");
    expect(content).toMatch(/# Artifact skill prose/);
    // No agent-file kind ever produced by this adapter.
    expect(result.written.every((w) => w.kind !== "agent")).toBe(true);
  });
});
