import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { getPacksPath } from "../../packs/get-pack-path.js";
import { readSkillManifest } from "../../packs/read-skill-manifest.js";
import { mergeAgentsMd, renderStandingModeSection } from "../../core/standing-mode.js";
import type { ResolvedPackEntry } from "../../packs/resolve-packs.js";
import type { AdapterRenderResult, RenderedFile, SkippedSkill } from "../types.js";

export interface RenderAgentOptions {
  /** Repo root to render `AGENTS.md` into. */
  targetDir: string;
  /** Packs to render — caller passes INSTALLABLE packs only (D6 gate is resolve-packs' job, not this module's). */
  packs: ResolvedPackEntry[];
  /** Override for tests; defaults to the bundled `packs/`. */
  packsRoot?: string;
  /** The D19 effective skill set (see `core/skill-selection.ts`). */
  effectiveSkills: Set<string>;
}

export type RenderAgentResult = AdapterRenderResult;

export const AGENTS_MD_RELATIVE_PATH = "AGENTS.md";

function introHeader(): string {
  // Nockta-generated marker line (spec §8.5: "Content is Nockta-authored ... curated for a single
  // shared file"). Plain markdown — AGENTS.md has no required frontmatter convention, unlike
  // Cursor's .mdc or Copilot's instructions file.
  return (
    "# AGENTS.md\n\n" +
    "> Generated by [inject-nockta-skills](https://github.com/nockta) — Nockta-curated AI agent " +
    "guidance for this repository. Read by OpenAI Codex, Google Antigravity/`agy`, Cursor, Zed, " +
    "Windsurf, and (secondarily) GitHub Copilot.\n"
  );
}

/**
 * Generic `agent` adapter renderer (spec §8.5, decisions.md D24, D1/D19/D23). Renders exactly ONE
 * root file, `AGENTS.md` — one section per installed pack, drawn from that pack's SELECTED
 * (effective-set, adapter-supported) skills. Modeled on `adapters/copilot/render.ts`'s
 * single-combined-file shape, but in AGENTS.md conventions: plain markdown, no tool-specific
 * frontmatter, a short Nockta-generated intro line.
 *
 * `packs/<pack>/adapters/agent/<pack-name>.md` — when present — wins WHOLESALE over that pack's
 * mechanical section content (D1 override, same per-pack override unit as
 * `adapters/copilot/render.ts`, since agent's output unit is one section per pack inside a single
 * shared root file, not one file per pack).
 *
 * **Agent-artifact handling (D24):** AGENTS.md has no agent-registration mechanism, so a skill's
 * `outputs.agent.agents` is NEVER honored here — only `outputs.agent.skills` (SKILL.md prose) is
 * ever emitted under this adapter, even if a skill.json sets `outputs.agent.agents: true`. Agent
 * artifacts (e.g. subagent-delegation's `worker.md`) simply have no home under this adapter.
 *
 * Because the output is a MERGE across every installed pack (not a 1:1 copy of any single source
 * file), this renderer produces exactly ONE `RenderedFile` record for the whole combined file —
 * `pack` is the sorted, comma-joined list of contributing pack names, `skill` is absent, and
 * `content`/`sourceContentHash` carry the actual rendered bytes and a hash of every contributing
 * source file's raw bytes (concatenated in render order) — see `src/adapters/types.ts`'s
 * `RenderedFile` doc comment.
 */
export function renderAgentAdapter(options: RenderAgentOptions): RenderAgentResult {
  const packsRoot = options.packsRoot ?? getPacksPath();
  const skipped: SkippedSkill[] = [];
  const sections: string[] = [];
  const sourceBuffers: Buffer[] = [];
  const contributingPacks: string[] = [];
  let anyOverridden = false;

  for (const pack of options.packs) {
    const packPath = join(packsRoot, pack.name);
    const overridePath = join(packPath, "adapters", "agent", `${pack.name}.md`);
    const overridden = existsSync(overridePath);

    const packSections: string[] = [];
    const packSourceBuffers: Buffer[] = [];

    for (const skillName of pack.manifest.skills) {
      if (!options.effectiveSkills.has(skillName)) {
        skipped.push({
          pack: pack.name,
          skill: skillName,
          reason: "excluded by skill selection (not in the effective set, decisions.md D19)",
        });
        continue;
      }

      const skillDir = join(packPath, "skills", skillName);
      const manifest = readSkillManifest(skillDir, skillName, pack.manifest.adapters);

      if (!manifest.supportedAdapters.includes("agent")) {
        skipped.push({
          pack: pack.name,
          skill: skillName,
          reason: `adapter-restricted: supportedAdapters=[${manifest.supportedAdapters.join(", ")}] (no "agent")`,
        });
        continue;
      }

      const agentOutputs = manifest.outputs.agent;
      if (agentOutputs === false || agentOutputs === undefined || !agentOutputs.skills) {
        skipped.push({ pack: pack.name, skill: skillName, reason: "outputs.agent is false (or undeclared, or outputs.agent.skills is not true)" });
        continue;
      }

      // D24: outputs.agent.agents is never honored — AGENTS.md has no agent-registration
      // mechanism, so worker.md-type artifacts are never emitted for this adapter regardless of
      // what a skill.json declares.
      const raw = readFileSync(join(skillDir, "SKILL.md"));
      packSections.push(`### ${skillName}\n\n${raw.toString("utf8").trim()}\n`);
      packSourceBuffers.push(raw);
    }

    let packBlock: string | null = null;
    if (overridden) {
      const overrideBuf = readFileSync(overridePath);
      packBlock = `${overrideBuf.toString("utf8").trim()}\n`;
      sourceBuffers.push(overrideBuf);
      anyOverridden = true;
    } else if (packSections.length > 0) {
      packBlock = `## ${pack.manifest.displayName}\n\n${pack.manifest.description}\n\n${packSections.join("\n")}`;
      sourceBuffers.push(...packSourceBuffers);
    }

    if (packBlock) {
      sections.push(packBlock);
      contributingPacks.push(pack.name);
    }
  }

  if (sections.length === 0) {
    return { written: [], skipped };
  }

  // Standing-mode contract (decisions.md D34) is the PREAMBLE of the file the agent adapter owns —
  // AGENTS.md is the single source of truth for the block; every other adapter merely references
  // this file. Uses the shared `renderStandingModeSection()` so the text is authored in exactly one
  // place (`core/standing-mode.ts`).
  const body = `${introHeader()}\n${renderStandingModeSection()}\n\n${sections.join("\n")}`;
  const sourceContentHash = createHash("sha256").update(Buffer.concat(sourceBuffers)).digest("hex");

  // D34 addendum — closing the "known boundary": the agent adapter no longer blind-overwrites a
  // pre-existing consumer AGENTS.md. `mergeAgentsMd()` keeps the whole Nockta payload inside a guard
  // region and preserves any consumer content OUTSIDE it. The SAME merge runs at repair/upgrade time
  // (`core/apply-render-plan.ts`), so install and maintenance behave identically. On a fresh target
  // (empty dir, or `computeRenderPlan()`'s scratch dir) the merge yields the pure Nockta region.
  const outputPath = join(options.targetDir, "AGENTS.md");
  mkdirSync(dirname(outputPath), { recursive: true });
  const existing = existsSync(outputPath) ? readFileSync(outputPath, "utf8") : null;
  const merged = mergeAgentsMd(existing, body);
  writeFileSync(outputPath, Buffer.from(merged.content, "utf8"));

  // `content` is the target-INDEPENDENT canonical region (what a fresh install writes) so
  // `computeRenderPlan()` stays pure and the repair/upgrade path can recover the body via
  // `unwrapAgentsRegion()`. The actual on-disk bytes (which may include preserved consumer content)
  // are hashed by the install orchestrator via `sha256File(outputPath)` when it tracks the file.
  const content = Buffer.from(mergeAgentsMd(null, body).content, "utf8");

  const written: RenderedFile[] = [
    {
      relativePath: AGENTS_MD_RELATIVE_PATH,
      outputPath,
      sourcePath: packsRoot,
      overridden: anyOverridden,
      adapter: "agent",
      pack: [...contributingPacks].sort().join(","),
      kind: "instructions",
      content,
      sourceContentHash,
      mergedIntoConsumerContent: merged.hadConsumerContent,
    },
  ];

  return { written, skipped };
}
